//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archi_TP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public string LastNameEmployee { get; set; }
        public string FirstNameEmployee { get; set; }
        public string EmailEmployee { get; set; }
        public string AddressEmployee { get; set; }
        public int TelephoneEmployee { get; set; }
        public Nullable<System.DateTime> BirthDateEmployee { get; set; }
        public Nullable<System.DateTime> HiringDateEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual User User { get; set; }
    }
}
